#!/usr/bin/env python3
"""Create deterministic, release-ready fabrication ZIPs for all boards."""

from pathlib import Path
import re
import subprocess
import tempfile
import zipfile


ROOT = Path(__file__).resolve().parents[1]
PROJECTS = (
    ("dimmer", "esp32_dimmer", "ESP32_C3_Halogen_Dimmer_JLCPCB.zip"),
    ("remote_controller", "esp32c3_remote", "ESP32_C3_Remote_Controller_JLCPCB.zip"),
    ("photodiode_lab", "photodiode_lab", "ESP32_C3_Photodiode_TIA_Lab_JLCPCB.zip"),
    ("raspberry_spi0_breakout", "raspberry_spi0_breakout", "raspberry_spi0_30x53_R2_JLCPCB.zip"),
)
LAYERS = "F.Cu,B.Cu,F.Mask,B.Mask,F.SilkS,B.SilkS,Edge.Cuts"
FABRICATION_SUFFIXES = {
    ".gtl", ".gbl", ".gts", ".gbs", ".gto", ".gbo", ".gm1", ".gbr", ".drl"
}


def run(*args: str) -> None:
    print("+", " ".join(args), flush=True)
    subprocess.run(args, cwd=ROOT, check=True)


def normalized_fabrication_bytes(path: Path) -> bytes:
    """Remove run-time timestamps while preserving fabrication attributes."""
    text = path.read_text()
    text = re.sub(
        r"%TF\.CreationDate,[^*]+\*%",
        "%TF.CreationDate,1980-01-01T00:00:00Z*%",
        text,
    )
    text = re.sub(
        r"G04 Created by KiCad \([^\n]+\) date [^*]+\*",
        "G04 Created by KiCad*",
        text,
    )
    text = re.sub(
        r"; DRILL file KiCad [^\n]+ date [^\n]+",
        "; DRILL file generated by KiCad",
        text,
    )
    text = re.sub(
        r"; #@! TF\.CreationDate,[^\n]+",
        "; #@! TF.CreationDate,1980-01-01T00:00:00Z",
        text,
    )
    return text.encode("utf-8")


def add_deterministic(archive: zipfile.ZipFile, path: Path) -> None:
    info = zipfile.ZipInfo(path.name, date_time=(1980, 1, 1, 0, 0, 0))
    info.compress_type = zipfile.ZIP_DEFLATED
    info.create_system = 3
    info.external_attr = 0o100644 << 16
    archive.writestr(info, normalized_fabrication_bytes(path))


def main() -> None:
    for directory, stem, archive_name in PROJECTS:
        project = ROOT / directory
        board = project / f"{stem}.kicad_pcb"
        schematic = project / f"{stem}.kicad_sch"
        output = project / "outputs"
        output.mkdir(exist_ok=True)
        run(
            "kicad-cli", "sch", "erc", str(schematic),
            "-o", str(output / f"{stem}-erc.rpt"), "--exit-code-violations",
        )
        run(
            "kicad-cli", "pcb", "drc", str(board),
            "-o", str(output / f"{stem}-drc.rpt"),
            "--schematic-parity", "--exit-code-violations",
        )
        with tempfile.TemporaryDirectory(prefix=f"{directory}-fabrication-") as temporary:
            plots = Path(temporary)
            run(
                "kicad-cli", "pcb", "export", "gerbers", str(board),
                "-o", str(plots) + "/", "--layers", LAYERS, "--subtract-soldermask",
            )
            run(
                "kicad-cli", "pcb", "export", "drill", str(board),
                "-o", str(plots) + "/", "--format", "excellon",
                "--excellon-units", "mm", "--excellon-separate-th",
            )
            files = sorted(
                path for path in plots.iterdir()
                if path.suffix.lower() in FABRICATION_SUFFIXES
            )
            suffixes = {path.suffix.lower() for path in files}
            required = {".gtl", ".gbl", ".gts", ".gbs", ".gto", ".gm1", ".drl"}
            if not required <= suffixes:
                raise RuntimeError(f"Missing fabrication layers for {directory}: {required - suffixes}")
            target = output / archive_name
            with zipfile.ZipFile(target, "w") as archive:
                for path in files:
                    add_deterministic(archive, path)
            with zipfile.ZipFile(target) as archive:
                if archive.testzip() is not None:
                    raise RuntimeError(f"Corrupt archive: {target}")
            print(target.relative_to(ROOT))


if __name__ == "__main__":
    main()
